const { chromium } = require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');

(async () => {
  const root = path.resolve(__dirname,'..');
  const output = path.join(root,'evidence');
  await fs.mkdir(output,{recursive:true});
  const browser = await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors = [], requests = [], checks = [];
  page.on('pageerror',error => errors.push(error.message));
  page.on('request',request => requests.push(request.url()));
  await context.route('**/*',route => {
    const url = route.request().url();
    if (/^(http:\/\/(127\.0\.0\.1|localhost)(:\d+)?\/|blob:|data:)/.test(url)) return route.continue();
    return route.abort();
  });
  try {
    await page.goto('http://127.0.0.1:5173');
    await page.getByText('Local AI connected',{exact:true}).waitFor();
    await page.getByRole('button',{name:/computer Sample clip/}).waitFor();
    await page.screenshot({path:path.join(output,'studio-empty.png'),fullPage:true});
    checks.push('Mint studio loads with real local model and local voices; remote browser requests blocked');
    await page.getByRole('button',{name:/Vocabulary/}).click();
    await page.getByRole('textbox',{name:'Search vocabulary'}).fill('computer');
    assert.equal(await page.locator('.word-library span').count(),1);
    await page.getByRole('button',{name:'Close dialog'}).click();
    checks.push('Vocabulary search reflects model labels');
    await page.getByRole('button',{name:/computer Sample clip/}).click();
    await page.waitForFunction(() => document.querySelector('video')?.duration > 0);
    await page.getByRole('button',{name:'Play video',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('video').currentTime > .1);
    await page.getByRole('button',{name:'Pause video',exact:true}).click();
    await page.locator('input[aria-label="Seek video"]').fill('0.5');
    await page.getByRole('button',{name:'Mark segment start'}).click();
    assert.equal(Number(await page.getByRole('spinbutton',{name:'Segment start'}).inputValue()),.5);
    await page.getByRole('spinbutton',{name:'Segment start'}).fill('0');
    checks.push('Downloaded real MP4 plays, pauses, seeks and segment start marks');
    await page.getByRole('button',{name:'Analyze whole clip',exact:true}).click();
    await page.locator('.prediction-option').first().waitFor({timeout:30000});
    assert.match(await page.locator('.prediction-option').first().innerText(),/computer/);
    await page.getByRole('button',{name:'Add word',exact:true}).click();
    assert.equal(await page.getByRole('textbox',{name:'Editable transcript'}).inputValue(),'computer');
    checks.push('Real ensemble recognizes computer from video pixels, explicit confirmation updates transcript');
    await page.getByRole('textbox',{name:'Add a word manually'}).fill('help');
    await page.getByRole('button',{name:'Add manual word',exact:true}).click();
    assert.equal(await page.getByRole('textbox',{name:'Editable transcript'}).inputValue(),'computer help');
    await page.getByRole('button',{name:'Undo transcript change'}).click();
    assert.equal(await page.getByRole('textbox',{name:'Editable transcript'}).inputValue(),'computer');
    const speechResponse = page.waitForResponse(response => response.url().endsWith('/api/speech') && response.status()===200);
    await page.getByRole('button',{name:'Speak transcript',exact:true}).click();
    const response = await speechResponse;
    assert.ok(Number(response.headers()['content-length']) > 44);
    await page.waitForFunction(() => document.querySelector('audio').duration > 0);
    const audioBytes = await page.locator('audio').evaluate(async audio => {
      const data = new Uint8Array(await (await fetch(audio.src)).arrayBuffer());
      return {header:String.fromCharCode(...data.slice(0,4)),bytes:data.length};
    });
    assert.equal(audioBytes.header,'RIFF');
    assert.ok(audioBytes.bytes>44);
    const audioState = await page.locator('audio').evaluate(audio => ({duration:audio.duration,currentTime:audio.currentTime,readyState:audio.readyState}));
    assert.ok(audioState.duration>0 && audioState.readyState>=2);
    checks.push('Offline speech button returns actual WAV and browser decodes/plays local audio');
    const txtDownload = page.waitForEvent('download');
    await page.getByRole('button',{name:'Download transcript as TXT'}).click();
    await (await txtDownload).saveAs(path.join(output,'browser-transcript.txt'));
    assert.equal(await fs.readFile(path.join(output,'browser-transcript.txt'),'utf8'),'computer');
    checks.push('Manual word, undo and TXT download preserve transcript');
    await page.getByRole('button',{name:'Recognize sign',exact:true}).click();
    await page.locator('.prediction-option').first().waitFor({timeout:30000});
    await page.screenshot({path:path.join(output,'studio-recognition.png'),fullPage:true});
    checks.push('Selected segment recognition returns real predictions');
    const positions = await page.evaluate(() => ({video:document.querySelector('.video-card').getBoundingClientRect().x,text:document.querySelector('.transcript-card').getBoundingClientRect().x,font:getComputedStyle(document.body).fontFamily}));
    assert.ok(positions.text>positions.video);
    assert.match(positions.font,/-apple-system/);
    checks.push('Desktop transcript is right of video, speech below text, Apple system font stack configured');
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'studio-mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth));
    assert.deepEqual(errors,[]);
    checks.push('Mobile layout has no horizontal overflow; browser has no runtime errors');
    await fs.writeFile(path.join(output,'browser-verification.json'),JSON.stringify({passed:true,checks,audioState,positions,pageErrors:errors,remoteRequests:requests.filter(url=>! /^(http:\/\/(127\.0\.0\.1|localhost)|blob:|data:)/.test(url)),network:'All external browser requests denied; loopback allowed'},null,2));
    console.log(JSON.stringify({passed:true,checks,audioState,errors},null,2));
  } finally { await browser.close(); }
})().catch(error => {console.error(error);process.exitCode=1;});
