const{chromium}=require('C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const sentence="And that's a great vital point technique for women's self defense.";
const filipino='At iyan ay isang mahusay na teknik na nakatuon sa sensitibong bahagi ng katawan para sa pagtatanggol sa sarili ng kababaihan.';
(async()=>{const root=path.resolve(__dirname,'..'),output=path.join(root,'evidence');const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',error=>errors.push(error.message));await context.route('**/*',route=>/^(http:\/\/(127\.0\.0\.1|localhost)|blob:|data:)/.test(route.request().url())?route.continue():route.abort());try{
 await page.goto('http://127.0.0.1:5173');await page.getByRole('button',{name:'Try a sentence video'}).waitFor();assert.equal(await page.locator('aside,nav,.transcript-card').count(),0);await page.getByRole('button',{name:'Record with webcam'}).click();await page.getByText('Webcam recording is coming soon. Upload a video for now.').waitFor();checks.push('Minimal upload home; webcam action is a placeholder and requests no camera access');await page.screenshot({path:path.join(output,'demo-home.png'),fullPage:true});
 await page.getByRole('button',{name:'Try a sentence video'}).click();await page.locator('.caption-card:not(.filipino-caption) .caption-copy').waitFor();await page.waitForFunction(()=>document.querySelector('video')?.currentTime>.1);await page.locator('video').evaluate(video=>video.pause());
 const english=page.locator('.caption-card:not(.filipino-caption) .caption-copy'),fil=page.locator('.filipino-caption .caption-copy');
 await page.getByRole('slider',{name:'Seek video'}).fill('0.2');await page.waitForFunction(()=>document.querySelector('.caption-card:not(.filipino-caption) .caption-copy').textContent==="And that's a great");
 await page.getByRole('slider',{name:'Seek video'}).fill('1.5');await page.waitForFunction(()=>document.querySelector('.caption-card:not(.filipino-caption) .caption-copy').textContent.includes('vital point technique'));
 await page.getByRole('slider',{name:'Seek video'}).fill('3');await page.waitForFunction(()=>document.querySelector('.caption-card:not(.filipino-caption) .caption-copy').textContent.endsWith('self defense.'));assert.equal(await english.innerText(),sentence);assert.equal(await fil.innerText(),filipino);checks.push('Static English and Filipino captions build into full sentences and follow video seeking');
 const position=await page.evaluate(()=>{const rect=selector=>{const r=document.querySelector(selector).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};return{video:rect('.video-canvas'),english:rect('.caption-card:not(.filipino-caption)'),filipino:rect('.filipino-caption'),text:rect('.caption-card:not(.filipino-caption) .caption-copy'),speech:rect('.caption-speech')}});assert.ok(position.video.width>1200);assert.ok(position.english.x>position.video.x+position.video.width/2);assert.ok(position.filipino.right<position.video.x+position.video.width/2);assert.ok(position.speech.y>=position.text.bottom);checks.push('Large video shows lyric-style English on the right, Filipino on the left, speech play beneath English');
 await page.getByRole('slider',{name:'Seek video'}).fill('0.2');const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/speech')&&response.status()===200);await page.getByRole('button',{name:'Play translated text'}).click();const response=await responsePromise;assert.equal(JSON.parse(response.request().postData()).text,sentence);await page.waitForFunction(()=>document.querySelector('audio').currentTime>.05&&!document.querySelector('audio').paused);const audio=await page.locator('audio').evaluate(async element=>{const data=new Uint8Array(await(await fetch(element.src)).arrayBuffer());return{duration:element.duration,time:element.currentTime,bytes:data.length,header:String.fromCharCode(...data.slice(0,4))}});assert.equal(audio.header,'RIFF');await page.getByRole('button',{name:'Stop speech'}).click();checks.push('Play translated text speaks the entire English sentence using actual advancing offline WAV playback');
 await page.getByRole('slider',{name:'Seek video'}).fill('3');await page.locator('.caption-copy').evaluateAll(elements=>Promise.all(elements.flatMap(element=>element.getAnimations().map(animation=>animation.finished.catch(()=>{})))));await page.screenshot({path:path.join(output,'demo-bilingual.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'demo-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(element=>element.getBoundingClientRect().right>innerWidth+1).map(element=>({tag:element.tagName,class:element.className,right:element.getBoundingClientRect().right})).slice(0,8)}));assert.ok(overflow.scroll<=overflow.width,JSON.stringify(overflow));assert.deepEqual(errors,[]);checks.push('Mobile layout fits the screen and no browser runtime errors occur');
 await fs.writeFile(path.join(output,'demo-verification.json'),JSON.stringify({passed:true,checks,position,audio,errors,staticCaptionDemo:true,aiInference:false,network:'External browser requests denied'},null,2));console.log(JSON.stringify({passed:true,checks,position,audio},null,2));
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
